/**
 * Default habit library.
 * Definitions live here in code — user-specific state (hidden, completions)
 * is stored separately in Firestore at users/{uid}/habitPrefs/defaults.
 */

export const DEFAULT_HABITS = [
  {
    id: 'quality-sleep',
    title: 'Quality Sleep',
    zone: 'health',
    icon: '💤',
    description: 'Consistent rest anchors recovery, focus, and emotional regulation.',
    trait: 'vitality',
    insight: 'Sleep is when the body repairs and the brain consolidates the day. Consistent rest timing is one of the highest-leverage habits for physical and mental performance.',
  },
  {
    id: 'morning-sunlight',
    title: 'Morning Sunlight',
    zone: 'health',
    icon: '🌱',
    description: 'Early light exposure helps anchor your body clock and energy patterns.',
    trait: 'vitality',
    insight: 'Morning sunlight helps anchor your daily rhythm and supports sleep timing later in the day.',
  },
  {
    id: 'evening-wind-down',
    title: 'Evening Wind Down',
    zone: 'health',
    icon: '💤',
    description: 'A wind-down routine signals your nervous system toward rest.',
    trait: 'resilience',
    insight: 'A consistent wind-down helps the nervous system transition toward rest. Reducing stimulation before bed supports deeper, more restorative sleep.',
  },
  {
    id: 'daily-movement',
    title: 'Daily Movement',
    zone: 'health',
    icon: '💪',
    description: 'Regular physical movement builds energy and structural resilience.',
    trait: 'vitality',
    insight: 'Movement supports energy, posture, and emotional regulation. Even moderate daily activity creates measurable long-term benefits.',
  },
  {
    id: 'strength-training',
    title: 'Strength Training',
    zone: 'health',
    icon: '💪',
    description: 'Progressive resistance builds physical capacity and consistent effort.',
    trait: 'discipline',
    insight: 'Strength training builds more than muscle — it reinforces the capacity to apply consistent effort over time.',
  },
  {
    id: 'deep-breathing',
    title: 'Deep Breathing & Relaxation',
    zone: 'health',
    icon: '⚖️',
    description: 'Intentional breathing reduces tension and supports nervous system balance.',
    trait: 'resilience',
    insight: 'Controlled breathing activates the parasympathetic nervous system, reducing physiological stress and improving focus.',
  },
  {
    id: 'prayer-reflection',
    title: 'Prayer or Reflection',
    zone: 'faith',
    icon: '📖',
    description: 'Daily reflection creates space for direction before reacting to the day.',
    trait: 'purpose',
    insight: 'Reflection creates space to notice direction before reacting to the day. Grounding in values supports more intentional choices.',
  },
  {
    id: 'morning-gratitude',
    title: 'Morning Gratitude',
    zone: 'faith',
    icon: '📖',
    description: 'Starting with acknowledgment shifts orientation toward what is good.',
    trait: 'emotional-stability',
    insight: 'Beginning the day with acknowledgment of what is good shifts your baseline orientation and supports a more stable emotional state throughout the day.',
  },
  {
    id: 'check-in-loved-ones',
    title: 'Check-in with Loved Ones',
    zone: 'family',
    icon: '❤️',
    description: 'Intentional connection builds relational depth over time.',
    trait: 'connection',
    insight: 'Intentional connection supports emotional stability and relational depth. Regular check-ins prevent relational drift and build trust over time.',
  },
  {
    id: 'acts-of-kindness',
    title: 'Acts of Kindness',
    zone: 'community',
    icon: '🤲',
    description: 'Giving to others reinforces a sense of contribution and meaning.',
    trait: 'purpose',
    insight: 'Acts of giving shift focus outward and reinforce a sense of contribution. This supports a more stable sense of identity and purpose.',
  },
  {
    id: 'whole-food-meal',
    title: 'Whole Food Meal',
    zone: 'health',
    icon: '🌱',
    description: 'Nutrient-dense food choices support sustained energy and cellular health.',
    trait: 'vitality',
    insight: 'Choosing nutrient-dense foods provides the body with what it needs to function well. Consistent food quality compounds over time.',
  },
  {
    id: 'hydration',
    title: 'Hydration',
    zone: 'health',
    icon: '⭐',
    description: 'Adequate water intake supports cognitive clarity and physical function.',
    trait: 'vitality',
    insight: 'Even mild dehydration affects cognitive performance and energy levels. Consistent hydration is one of the simplest inputs with broad benefits.',
  },
  {
    id: 'financial-check-in',
    title: 'Financial Check-In',
    zone: 'wealth',
    icon: '📊',
    description: 'Regular financial awareness builds discipline and reduces money-related stress.',
    trait: 'discipline',
    insight: 'Regular financial awareness prevents drift and supports intentional resource management. Small consistent reviews compound into financial clarity.',
  },
  {
    id: 'reading-learning',
    title: 'Reading or Learning',
    zone: 'wealth',
    icon: '📖',
    description: 'Deliberate learning builds adaptive capacity and mental sharpness.',
    trait: 'discipline',
    insight: 'Consistent learning builds cognitive capacity and adaptive thinking. Even 15 minutes of focused reading compounds significantly over months.',
  },
  {
    id: 'outdoor-time',
    title: 'Outdoor Time',
    zone: 'health',
    icon: '🌱',
    description: 'Time outside supports mood regulation, light exposure, and physical health.',
    trait: 'resilience',
    insight: 'Time in natural environments reduces mental fatigue and supports psychological restoration. Regular outdoor exposure benefits mood and physical health.',
  },
];

export const ZONE_META = {
  health:          { name: 'Health',              chipColor: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  socialEmotional: { name: 'Social & Emotional',  chipColor: 'bg-rose-50 text-rose-700 border-rose-200' },
  wealth:          { name: 'Wealth',              chipColor: 'bg-amber-50 text-amber-700 border-amber-200' },
  faith:           { name: 'Faith',               chipColor: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  family:          { name: 'Family',              chipColor: 'bg-blue-50 text-blue-700 border-blue-200' },
  community:       { name: 'Community',           chipColor: 'bg-orange-50 text-orange-700 border-orange-200' },
};

export const TRAIT_META = {
  vitality:           { label: 'Vitality',            color: 'bg-emerald-50 text-emerald-600' },
  resilience:         { label: 'Resilience',          color: 'bg-sky-50 text-sky-600' },
  discipline:         { label: 'Discipline',          color: 'bg-indigo-50 text-indigo-600' },
  'emotional-stability': { label: 'Emotional Stability', color: 'bg-rose-50 text-rose-600' },
  connection:         { label: 'Connection',          color: 'bg-pink-50 text-pink-600' },
  purpose:            { label: 'Purpose',             color: 'bg-amber-50 text-amber-700' },
};
